#!/usr/bin/env python3
"""Regenerate sitemap.xml and sitemap/index.html for this static site.

Run from anywhere: python scripts/build-sitemap.py
The page list is PAGES below; each page's <lastmod> is the date of the last git commit that
touched its source file (left out if the file has no history yet). URLs always use BASE_URL,
the site's production address (from CNAME). The HTML page reuses the legal hub's layout.

Copyright (c) Stux.Group. All Rights Reserved.
"""
import html
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://" + (ROOT / "CNAME").read_text(encoding="utf-8").strip()

# (path, source file, label, description, priority, changefreq)
PAGES = [
    ("/", "index.html", "Home", "The notice that Gaymer.Social and Gaymer.Coffee were discontinued in September 2026.", "1.0", "yearly"),
    ("/legal/", "legal/index.html", "Boring Legal Stuff", "Privacy, terms, cookies, imprint, disclaimer and opt-out preferences, in one place.", "0.3", "yearly"),
    ("/legal/privacy/", "legal/privacy/index.html", "Privacy Policy", "What we collect (nothing) and how this site is hosted.", "0.2", "yearly"),
    ("/legal/terms/", "legal/terms/index.html", "Terms and Ethics", "This is an informational notice, not a service.", "0.2", "yearly"),
    ("/legal/cookies/", "legal/cookies/index.html", "Cookies Policy", "No cookies, no local storage, no tracking of any kind.", "0.2", "yearly"),
    ("/legal/imprint/", "legal/imprint/index.html", "Imprint", "Who operates this site and how to reach us.", "0.2", "yearly"),
    ("/legal/disclaimer/", "legal/disclaimer/index.html", "Disclaimer", "Accuracy and liability for the notice above.", "0.2", "yearly"),
    ("/legal/opt-out/", "legal/opt-out/index.html", "Opt-Out Preferences", "There's nothing to sell, so nothing to opt out of.", "0.2", "yearly"),
    ("/sitemap/", "sitemap/index.html", "Sitemap", "Every page on this site, with a link to the XML version.", "0.1", "yearly"),
]


def lastmod(rel: str) -> str:
    return subprocess.run(["git", "log", "-1", "--format=%cs", "--", rel], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()


def build_xml() -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, src, _label, _desc, priority, freq in PAGES:
        lines.append("  <url>")
        lines.append(f"    <loc>{html.escape(BASE_URL + loc)}</loc>")
        mod = lastmod(src)
        if mod:
            lines.append(f"    <lastmod>{mod}</lastmod>")
        lines.append(f"    <changefreq>{freq}</changefreq>")
        lines.append(f"    <priority>{priority}</priority>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build_html() -> str:
    """The sitemap page, in the legal hub's layout (theme, banner, footer)."""
    legal = subprocess.run(["git", "show", "HEAD:legal/index.html"], cwd=ROOT,
                           capture_output=True, text=True, encoding="utf-8").stdout
    # Prefer the working copy so unreleased layout changes are picked up.
    working = ROOT / "legal" / "index.html"
    if working.exists():
        legal = working.read_text(encoding="utf-8")
    head = legal[:legal.index('<div class="card">')]
    head = head.replace("<title>Boring Legal Stuff", "<title>Sitemap", 1)
    foot = legal[legal.index('<div class="footer-powered">'):]
    items = []
    for loc, _src, label, desc, _p, _f in PAGES:
        items.append(f"""    <li><a class="doc" href="{html.escape(loc)}"><div class="url">{html.escape(BASE_URL + loc)}</div><div class="name">{html.escape(label)}</div><div class="desc">{html.escape(desc)}</div></a></li>""")
    style = "  a.doc .url { font-size: .72rem; font-weight: 700; letter-spacing: .04em; color: var(--accent); overflow-wrap: anywhere; }\n</style>"
    head = head.replace("</style>", style, 1)
    card = f"""<div class="card">
  <div class="eyebrow">Sitemap</div>
  <h1>Sitemap</h1>
  <p class="lead">Every page on this site. Looking for the XML version? <a href="/sitemap.xml">sitemap.xml</a></p>
  <ul>
{chr(10).join(items)}
  </ul>
  <a class="back" href="/">&larr; Back to the notice</a>
  """
    notice = "<!-- Generated by scripts/build-sitemap.py; edit the PAGES list there, then re-run it. -->\n"
    return head.replace("<body>\n", "<body>\n" + notice, 1) + card + foot


def main() -> None:
    (ROOT / "sitemap").mkdir(exist_ok=True)
    (ROOT / "sitemap" / "index.html").write_text(build_html(), encoding="utf-8", newline="\n")
    (ROOT / "sitemap.xml").write_text(build_xml(), encoding="utf-8", newline="\n")
    robots = ROOT / "robots.txt"
    line = f"Sitemap: {BASE_URL}/sitemap.xml"
    text = robots.read_text(encoding="utf-8") if robots.exists() else "User-agent: *\nAllow: /\n"
    if line not in text:
        text = text.rstrip("\n") + "\n\n" + line + "\n"
    robots.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote sitemap.xml, sitemap/index.html and robots.txt for {BASE_URL} ({len(PAGES)} pages)")


if __name__ == "__main__":
    main()
